version: '3'
services:
  omega:
    build: .
    depends_on:
    - redis
    restart: always
    environment:
      HUBOT_SLACK_TOKEN: $HUBOT_SLACK_TOKEN
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:4.0-alpine
    restart: always
    volumes:
      - redis:/data

volumes:
  redis: {}
